---
deployment:
  tasks:
    - export REPOPATH=/home/ocalntve/repositories/OcalaWaste
    - export DEPLOYPATH=/home/ocalntve/public_html
    - /bin/cp -a $REPOPATH/public/. $DEPLOYPATH/
    - /usr/bin/perl -pi -e "s#__DIR__\.'/../vendor/autoload.php'#__DIR__.'/../repositories/OcalaWaste/vendor/autoload.php'#g" $DEPLOYPATH/index.php
    - /usr/bin/perl -pi -e "s#__DIR__\.'/../bootstrap/app.php'#__DIR__.'/../repositories/OcalaWaste/bootstrap/app.php'#g" $DEPLOYPATH/index.php